name: example
description: "A new Flutter package project."
version: 0.0.1

environment:
  sdk: ^3.5.3
  flutter: ">=3.24.3"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^4.0.0
