name: figma_tokens_parser
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  path: ^1.9.1
  args: ^2.6.0
  collection: ^1.19.1
  meta: ^1.16.0
  recase: ^4.1.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.14
